### ISSUE TITLE
CNCF Graduation Checklist for the Kubeflow Project

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#655]
Opening a new issue just for the graduation criteria

**Graduation Stage**

Below is the Graduation Stage Criteria - A list of these requirements are provided below, which were copied from this site: (https://github.com/cncf/toc/blob/main/process/graduation_criteria.md#graduation-stage)
To graduate from sandbox or incubating status, or for a new project to join as a graduated project, a project must meet the incubating stage criteria plus:

- [] Have committers from at least two organizations.

- [] Have achieved and maintained a Core Infrastructure Initiative [Best Practices Badge](https://bestpractices.coreinfrastructure.org/).

- [] Have completed an independent and third party security audit with results published of similar scope and quality as the following example (including critical vulnerabilities addressed): https://github.com/envoyproxy/envoy#security-audit and all critical vulnerabilities need to be addressed before graduation.

- [] Explicitly define a project governance and committer process. The committer process should cover the full committer lifecycle including onboarding and offboarding or emeritus criteria. This preferably is laid out in a GOVERNANCE.md file and references an OWNERS.md file showing the current and emeritus committers.

- [] Explicitly define the criteria, process and offboarding or emeritus conditions for project maintainers; or those who may interact with the CNCF on behalf of the project. The list of maintainers should be preferably be stored in a MAINTAINERS.md file and audited at a minimum of an annual cadence.

- [] Have a public list of project adopters for at least the primary repo (e.g., ADOPTERS.md or logos on the project website). For a specification, have a list of adopters for the implementation(s) of the spec.

- []Receive a supermajority vote from the TOC to move to graduation stage. Projects can attempt to move directly from sandbox to graduation, if they can demonstrate sufficient maturity. Projects can remain in an incubating state indefinitely, but they are normally expected to graduate within two years.

**Comment by terrytangyuan** [comment]
cc @kubeflow/kubeflow-steering-committee

**Comment by varodrig** [comment]
adding updated link https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-graduation-application.md

**Comment by varodrig** [comment]
Issues are updated here https://docs.google.com/spreadsheets/d/1ehL-90G4XjpsUeDMj2j78XYG5F4z7-IpKLT6pGiyOq0/edit?gid=710823924#gid=710823924
